version: '3'

services:
  database: 
    image: mongo:latest
    container_name: mongo-container
    environment:
      - MONGO_INITDB_DATABASE=testdb
      - MONGO_INITDB_ROOTUSERNAME=root
      - MONGO_INITDB_ROOTPASSWORD=root
    volumes:
      - ./repo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./repo/mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
